name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run checks in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: |
            gleam format --check src test
            gleam build
            gleam test
            cd examples/proxy_wrapper_smoke
            gleam format --check src
            gleam build
